#!/usr/bin/env bash

# invoke jlox from different paths
script_dir=$(dirname "$0")
# $@ allows you to pass argumens
# eg. ./jlox arg1 "arg2" -> java ... arg1 "arg2"
java -cp ${script_dir}/target/classes lox.Lox $@
